name: Auto-add Issues to Priority Tracker

on:
  issues:
    types: [opened, reopened]

jobs:
  add-to-project-and-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels if missing and then add to Priority Tracker project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          script: |
            // 1. Check and add labels if missing
            const requiredLabels = ["steampipe", "github"];
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const currentLabels = issue.labels.map(l => typeof l === "string" ? l : l.name);
            const missingLabels = requiredLabels.filter(label => !currentLabels.includes(label));
            if (missingLabels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: missingLabels,
              });
            }

            // 2. Add to project
            const projectId = "PVT_kwDOAlEJmM4At_Ha";
            await github.graphql(`
              mutation($projectId:ID!, $contentId:ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item { id }
                }
              }
            `, {
              projectId,
              contentId: context.payload.issue.node_id
            });
